## <center>Preparing data for the Venn diagram.</center>


| **Label** | **start time** | **finish time** | **last modified** |
|:--------------:|:-----------:|:-----------:|:----------------:|
|   Project 1   |  2023-07-10 |  2023-07-19 |   2023-07-19     |

####  Threshold:
- SB > 0, 
- coverage ratio < 0.1,
- AF > 0.001.

In [1]:
import pandas as pd

threshold_AF = 0.001
threshold_SB = 0
threshold_COV = 0.1

## 1. Error position
### Next 
- go ---> 
```python
/nfs/research/goldman/zihao/Code/Figure/P1/2-1_vennChart_errPos.Rmd
```

In [2]:
input_for_annot_err = "/nfs/research/goldman/zihao/Datas/p1_errorsProject_NEW/Folder_dataProcessing/ANNOT_dataProcessing_errorPos.txt"
input_for_cov_err = "/nfs/research/goldman/zihao/Datas/p1_errorsProject_NEW/Folder_dataProcessing/COV_dataProcessing_errorPos.txt"

### For annot
df_err_annot = pd.read_csv(input_for_annot_err, sep='\t')

df_err_annot['ID_POS'] = df_err_annot['ID'].astype(str) + "_" + df_err_annot['Position'].astype(str)

df_err_annot['Flag_AF'] = df_err_annot['AF'] > threshold_AF
df_err_annot['Flag_SB'] = df_err_annot['SB'] > threshold_SB
df_err_annot.drop(['ID', 'Position','AF','SB'], axis=1, inplace=True)

print(df_err_annot)
print('=====================================')
### For coverage
df_err_cov = pd.read_csv(input_for_cov_err, sep='\t')

df_err_cov['ID_POS'] = df_err_cov['ID'].astype(str) + "_" + df_err_cov['Position'].astype(str)

df_err_cov['Flag_COV'] = df_err_cov['COV_Ratio'] < threshold_COV
df_err_cov.drop(['ID', 'Position', 'COV_Ratio'], axis=1, inplace=True)

print(df_err_cov)
print('=====================================')
### Merge
merged_df = pd.merge(df_err_annot, df_err_cov, on='ID_POS', how='inner')
merged_df.to_csv("/nfs/research/goldman/zihao/Code/IntermediateDATA/P1-ERR_POS_all.txt", sep='\t', index=False)

merged_df

                  ID_POS  Flag_AF  Flag_SB
0        ERR4590003_3078    False    False
1       ERR4590003_18425    False    False
2       ERR4589177_29616    False    False
3       ERR4589104_17722    False    False
4        ERR4589145_5941     True     True
...                  ...      ...      ...
44454   ERR4423892_24144    False     True
44455   ERR4423892_28275     True     True
44456   ERR4425059_27008     True     True
44457   SRR21662653_8984     True    False
44458  SRR21662653_21744     True    False

[44459 rows x 3 columns]
=====================================
                  ID_POS  Flag_COV
0        ERR4590003_3078     False
1       ERR4590003_18425     False
2       ERR4589177_29616     False
3       ERR4589104_17722     False
4        ERR4589145_5941     False
...                  ...       ...
43987   ERR4423892_24144     False
43988   ERR4423892_28275     False
43989   ERR4425059_27008     False
43990   SRR21662653_8984     False
43991  SRR21662653_21744     False

[43992 rows x 2 columns]
=====================================

                  ID_POS  Flag_AF  Flag_SB  Flag_COV
0        ERR4590003_3078    False    False     False
1       ERR4590003_18425    False    False     False
2       ERR4589177_29616    False    False     False
3       ERR4589104_17722    False    False     False
4        ERR4589145_5941     True     True     False
...                  ...      ...      ...       ...
43987   ERR4423892_24144    False     True     False
43988   ERR4423892_28275     True     True     False
43989   ERR4425059_27008     True     True     False
43990   SRR21662653_8984     True    False     False
43991  SRR21662653_21744     True    False     False

[43992 rows x 4 columns]

## 2. All position
- **output**
```python
'/nfs/research/goldman/zihao/Datas/p1_errorsProject_NEW/Folder2_calculPercentage/output_calculPercentage.txt'
```

====================== Info ======================  
Total number of positions:  4033264429  
nb_SB_PASSED:  1782985  
nb_AF_PASSED:  7547094  
nb_COV_PASSED:  583535685  
====================== Info ======================  
both_PASSED:  377289  
both_UNPASSED:  3420841838  
====================== Info ======================  
nb_AF_SB_PASSED:  17971522  
nb_SB_COV_PASSED:  253433  
nb_AF_COV_PASSED:  954583

In [3]:
same_count = 4033264429
Flag_SB_PASSED = 1782985
Flag_AF_PASSED = 7547094
Flag_COV_PASSED = 583535685
both_PASSED = 377289
both_UNPASSED = 3420841838
Flag_SB_Flag_AF_PASSED = 17971522
Flag_SB_Flag_COV_PASSED = 253433
Flag_AF_Flag_COV_PASSED = 954583

pass_1 = Flag_SB_PASSED+Flag_AF_PASSED+Flag_COV_PASSED
pass_2 = Flag_SB_Flag_AF_PASSED+Flag_SB_Flag_COV_PASSED+Flag_AF_Flag_COV_PASSED
pass_3 = both_PASSED + both_UNPASSED
nb_pass = pass_1+pass_2+pass_3

print(round(both_UNPASSED/nb_pass*100,3),'%')
print('=======================================')

print(round(Flag_AF_PASSED/nb_pass*100,3),'%')
print(round(Flag_COV_PASSED/nb_pass*100,3),'%')
print(round(Flag_SB_PASSED/nb_pass*100,3),'%')
print('=======================================')

print(round(Flag_SB_Flag_AF_PASSED/nb_pass*100,3),'%')
print(round(Flag_SB_Flag_COV_PASSED/nb_pass*100,3),'%')
print(round(Flag_AF_Flag_COV_PASSED/nb_pass*100,3),'%')

print('=======================================')
print(round(both_PASSED/nb_pass*100,3),'%')

84.816 %
=======================================
0.187 %
14.468 %
0.044 %
=======================================
0.446 %
0.006 %
0.024 %
=======================================
0.009 %

### Next 
- go ---> 
```python
/nfs/research/goldman/zihao/Code/Figure/P1/2-1_vennChart_errPos.Rmd
```