In [1]:
import plotly.graph_objects as go
from plotly.offline import iplot, plot
import pandas as pd
import numpy as np

import plotly
from plotly.subplots import make_subplots
import plotly.io as pio
from scipy.stats import gaussian_kde

In [2]:
# df_err = pd.read_csv("../../A_Datas/Error_pos_for_coverage.txt", sep='\t')
df_err = pd.read_csv("/nfs/research/goldman/zihao/Datas/p1/File_5_coverage/Error_pos_for_coverage_all.txt", sep='\t')
df_err

               ID  Position     error
0      ERR4423031      8755  0.042336
1      ERR4421647     11812  0.326993
2      ERR4421647     16174  1.012681
3      ERR4422806     10764  0.007743
4      ERR4424882      7071  2.189053
...           ...       ...       ...
47558  ERR4640670     20714  0.684224
47559  ERR4633273     10999  0.009642
47560  ERR4459789     26532  1.617389
47561  ERR4459789     28717  1.616577
47562  ERR4637087      9272  0.005466

[47563 rows x 3 columns]

In [3]:
# df_all = pd.read_csv('../../A_Datas/selected_data.txt', sep='\t')
df_all = pd.read_csv('/nfs/research/goldman/zihao/Datas/p1/File_5_coverage/cov_sampling_all.txt', sep='\t')
df_all

                 ID  Position  Ratio
0       SRR20988284         1    0.0
1        ERR4891192         1    0.0
2        ERR6516923         1    0.0
3       SRR22063559         1    0.0
4       ERR10017967         1    0.0
...             ...       ...    ...
299025   ERR8182301     29903    0.0
299026   ERR6416408     29903    0.0
299027  SRR23066099     29903    0.0
299028   ERR6516923     29903    0.0
299029  SRR19919813     29903    0.0

[299030 rows x 3 columns]

# Visualization

### Final version！！！

In [4]:
hist_data = [df_err['error'].tolist(), df_all['Ratio'].tolist()]
group_labels = ['Error position', 'All position']  # 数据集的名称
colors = ['#835AF1', '#B8F7D4']

fig = make_subplots(rows=2, cols=1, row_heights=[0.75, 0.25], shared_xaxes=True)

# 添加Density Plot子图
for data, label, color in zip(hist_data, group_labels, colors):
    kde = gaussian_kde(data)
    x_vals = np.linspace(min(data), max(data), 1000)
    y_vals = kde(x_vals)
    fig.add_trace(go.Scatter(x=x_vals, y=y_vals, mode='lines', fill='tozeroy', showlegend=False, line_color=color), 
                  row=1, col=1)

# 添加Box Plot子图
fig.add_trace(go.Box(x=df_all['Ratio'].tolist(), orientation='h', name=group_labels[1]), row=2, col=1)
fig.add_trace(go.Box(x=df_err['error'].tolist(), orientation='h', name=group_labels[0]), row=2, col=1)


fig.update_yaxes(range=[0, 2], row=1, col=1)
fig.update_xaxes(type='log', range=[np.log10(0.01), np.log10(np.max(np.concatenate(hist_data)))], row=1, col=1)
fig.update_xaxes(type='log', range=[np.log10(0.01), np.log10(np.max(np.concatenate(hist_data)))], row=2, col=1)
# 设置图形布局
fig.update_layout(
    title="Coverage density map over sample positions",
    yaxis=dict(
        title='Frequency',
        showline=True, showgrid=False,
        linewidth=2, linecolor='gray', ticks='outside',
        tickfont=dict(
            family='Arial',
            size=12,
            color='black',
        )
    ),
    
    xaxis=dict(
        title='The ratio of coverage vs mean coverage',
        type='log',  # 将x轴设置为对数刻度
        showline=True, showgrid=False,
        linewidth=2, linecolor='gray', ticks='outside',
        tickfont=dict(
            family='Arial',
            size=12,
            color='black',
        ),
    ),
    legend=dict(
        traceorder="normal",
        font=dict(size=12),
    ),

    plot_bgcolor='white',
    yaxis_gridcolor='lightgray', yaxis_gridwidth=0.5,
    xaxis_gridcolor='lightgray', xaxis_gridwidth=0.5,
)

#fig.show()
pio.write_image(fig, 'May.25_plot_for_coverage_log.png')
#plotly.offline.plot(fig, filename = "plot_for_coverage_log_nn.html")

import gc
gc.collect()