## <center>Preparing data for the Venn diagram.</center>


| **Label** | **start time** | **finish time** | **last modified** |
|:--------------:|:-----------:|:-----------:|:----------------:|
|   Project 1   |  2023-07-10 |  2023-07-19 |   2023-07-19     |

####  Threshold:
- SB > 0, 
- coverage ratio < 0.1,
- AF > 0.001.

In [1]:
import pandas as pd

threshold_AF = 0.001
threshold_SB = 0
threshold_COV = 0.1

## 1. Error position

In [2]:
input_for_annot_err = "/nfs/research/goldman/zihao/Datas/p1_errorsProject_NEW/Folder_dataProcessing/ANNOT_dataProcessing_errorPos.txt"
input_for_cov_err = "/nfs/research/goldman/zihao/Datas/p1_errorsProject_NEW/Folder_dataProcessing/COV_dataProcessing_errorPos.txt"

In [3]:
### For annot
df_err_annot = pd.read_csv(input_for_annot_err, sep='\t')

df_err_annot['ID_POS'] = df_err_annot['ID'].astype(str) + "_" + df_err_annot['Position'].astype(str)

df_err_annot['Flag_AF'] = df_err_annot['AF'] > threshold_AF
df_err_annot['Flag_SB'] = df_err_annot['SB'] > threshold_SB
df_err_annot.drop(['ID', 'Position','AF','SB'], axis=1, inplace=True)

print(df_err_annot)
print('=====================================')
### For coverage
df_err_cov = pd.read_csv(input_for_cov_err, sep='\t')

df_err_cov['ID_POS'] = df_err_cov['ID'].astype(str) + "_" + df_err_cov['Position'].astype(str)

df_err_cov['Flag_COV'] = df_err_cov['COV_Ratio'] < threshold_COV
df_err_cov.drop(['ID', 'Position', 'COV_Ratio'], axis=1, inplace=True)

print(df_err_cov)
print('=====================================')
### Merge
merged_df = pd.merge(df_err_annot, df_err_cov, on='ID_POS', how='inner')
merged_df.to_csv("/nfs/research/goldman/zihao/code/EBI_INTER/A_Datas/ERR_POS_all.txt", sep='\t', index=False)

merged_df

                  ID_POS  Flag_AF  Flag_SB
0        ERR4590003_3078    False    False
1       ERR4590003_18425    False    False
2       ERR4589177_29616    False    False
3       ERR4589104_17722    False    False
4        ERR4589145_5941     True     True
...                  ...      ...      ...
44454   ERR4423892_24144    False     True
44455   ERR4423892_28275     True     True
44456   ERR4425059_27008     True     True
44457   SRR21662653_8984     True    False
44458  SRR21662653_21744     True    False

[44459 rows x 3 columns]
=====================================
                  ID_POS  Flag_COV
0        ERR4590003_3078     False
1       ERR4590003_18425     False
2       ERR4589177_29616     False
3       ERR4589104_17722     False
4        ERR4589145_5941     False
...                  ...       ...
43987   ERR4423892_24144     False
43988   ERR4423892_28275     False
43989   ERR4425059_27008     False
43990   SRR21662653_8984     False
43991  SRR21662653_21744     False

[43992 rows x 2 columns]
=====================================

                  ID_POS  Flag_AF  Flag_SB  Flag_COV
0        ERR4590003_3078    False    False     False
1       ERR4590003_18425    False    False     False
2       ERR4589177_29616    False    False     False
3       ERR4589104_17722    False    False     False
4        ERR4589145_5941     True     True     False
...                  ...      ...      ...       ...
43987   ERR4423892_24144    False     True     False
43988   ERR4423892_28275     True     True     False
43989   ERR4425059_27008     True     True     False
43990   SRR21662653_8984     True    False     False
43991  SRR21662653_21744     True    False     False

[43992 rows x 4 columns]

## 2. All position

In [4]:
input_for_all = "/nfs/research/goldman/zihao/Datas/p1_errorsProject_NEW/Folder_dataProcessing/ANNOT_dataProcessing_allPos.txt"

In [5]:
df_all = pd.read_csv(input_for_all, sep='\t')

df_all['ID_POS'] = df_all['ID'].astype(str) + "_" + df_all['Position'].astype(str)

df_all['Flag_AF'] = df_all['AF'] > threshold_AF
df_all['Flag_SB'] = df_all['SB'] > threshold_SB
df_all['Flag_COV'] = df_all['Cov_RATIO'] < threshold_COV
df_all.drop(['ID', 'Position','AF','SB','N','Cov_RATIO'], axis=1, inplace=True)

df_all.to_csv("/nfs/research/goldman/zihao/code/EBI_INTER/A_Datas/ALL_POS_all.txt", sep='\t', index=False)

df_all

                   ID_POS  Flag_AF  Flag_SB  Flag_COV
0            ERR7852229_1    False    False      True
1            ERR4904704_1    False    False      True
2            ERR6441709_1    False    False      True
3           SRR19919813_1    False    False      True
4           SRR23074083_1    False    False      True
...                   ...      ...      ...       ...
299025   ERR7852229_29903    False    False      True
299026   ERR6516923_29903    False    False      True
299027  SRR20810786_29903    False    False      True
299028   ERR4891192_29903    False    False      True
299029   ERR6416408_29903    False    False      True

[299030 rows x 4 columns]

### Next 
- go ---> 
```python
/nfs/research/goldman/zihao/code/EBI_INTER/Project_1_errorAnalysis/1.densityvenn_P1/1.2_vennChart.Rmd
```