In [1]:
import plotly.graph_objects as go
import plotly.express as px
import plotly.figure_factory as ff
import pandas as pd
import numpy as np

### 1. For all

In [2]:
## For all
# df_all = pd.read_csv('../../selected_data.txt', sep='\t')
df_all = pd.read_csv('/nfs/research/goldman/zihao/Datas/p1/File_5_annot/selected_data.txt', sep='\t')
df_all['AF_Ratio'] = df_all['AF_Ratio'].replace([np.inf, -np.inf], np.nan)  # 将无穷大和无穷小值替换为NaN
df_all = df_all.dropna()  # 删除包含NaN的行
df_all

                ID  Position  AF_Ratio  SB_Ratio
0       ERR7107271         1       0.0       0.0
1       ERR6770028         1       0.0       0.0
2       ERR7352067         1       0.0       0.0
3       ERR5025733         1       0.0       0.0
4       ERR6348731         1       0.0       0.0
...            ...       ...       ...       ...
149510  ERR6586663     29903       0.0       0.0
149511  ERR6770028     29903       0.0       0.0
149512  ERR6348731     29903       0.0       0.0
149513  ERR6444963     29903       0.0       0.0
149514  ERR5025733     29903       0.0       0.0

[149515 rows x 4 columns]

### 2. For error_pos

In [3]:
# df_err = pd.read_csv("../../A_Datas/Error_pos_for_annot.txt", sep='\t')
df_err = pd.read_csv("/nfs/research/goldman/zihao/Datas/p1/File_5_annot/Error_pos_for_annot.txt", sep='\t')
df_err['AF'] = df_err['AF'].replace([np.inf, -np.inf], np.nan)  # 将无穷大和无穷小值替换为NaN
df_err = df_err.dropna()  # 删除包含NaN的行
df_err

                ID  Position        AF            SB
0       ERR4424882      7071  0.388591  2.147484e+09
1      SRR19472635      9086  0.039555  2.300000e+01
2      SRR19928806      2335  0.126866  9.000000e+00
3      SRR19928806      8651  0.235294  2.000000e+00
4      SRR19928806     28088  0.384615  1.000000e+01
...            ...       ...       ...           ...
21142   ERR4640021     10999  0.400000  2.300000e+01
21143   ERR4633809        66  0.000000  2.147484e+09
21144   ERR4638479     29736  0.002349  0.000000e+00
21145   ERR4637567     15372  0.000256  2.000000e+00
21146   ERR4640811     10884  0.000193  0.000000e+00

[21142 rows x 4 columns]

In [4]:
min_value = df_err['AF'].min()
count = (df_err['AF'] == min_value).sum()
print(count/len(df_err))

0.10528805221833318

from plotly.offline import iplot, plot

hist_data = [(df_err['AF'] * 100).tolist(), (df_all['AF_Ratio'] * 100).tolist()]
group_labels = ['error position', 'all position'] # name of the dataset
colors = ['#7FA6EE', '#B8F7D4']

fig = ff.create_distplot(hist_data, group_labels, curve_type='normal', colors=colors, bin_size=.25) #

# 设置图形布局
fig.update_layout(
    title="Allele Frequency",
    yaxis=dict(
        title='Probability density',
        showline=True, showgrid=False,
        linewidth=2, linecolor='gray', ticks='outside',
        tickfont=dict(
            family='Arial',
            size=12,
            color='black',
        )
    ),
    
    xaxis=dict(
        title='Allele Frequency / %',
        # type='log',  # 对数刻度
        showline=True, showgrid=False,
        range=[0, 1],  # 对数刻度中间值，根据需求调整
        linewidth=2, linecolor='gray', ticks='outside',
        tickfont=dict(
            family='Arial',
            size=12,
            color='black',
        )
        
    ),
    legend=dict(
        traceorder="normal",
        font=dict(size=12),
    ),

    plot_bgcolor='white',
    yaxis_gridcolor='lightgray', yaxis_gridwidth=0.5,
    xaxis_gridcolor='lightgray', xaxis_gridwidth=0.5,
    
)
# fig.update_xaxes(rangeslider_visible=True)
# fig.show()
plot(fig, filename='Plot_for_AF_0-10_all.html')

In [15]:
import plotly.graph_objects as go

fig = go.Figure()

for data, label, color in zip(hist_data, group_labels, colors):
    fig.add_trace(go.Histogram(x=data, histnorm='probability', name=label, marker_color=color, nbinsx=100))

fig.update_layout(barmode='overlay')
fig.write_image("output.png", format="png")

In [17]:
import plotly.figure_factory as ff
import plotly.io as pio

hist_data = [(df_err[df_err['AF'] * 100 < 1]['AF'] * 100).tolist(), 
             (df_all[df_all['AF_Ratio'] * 100 < 1]['AF_Ratio'] * 100).tolist()]
group_labels = ['error position', 'all position'] # name of the dataset
colors = ['#7FA6EE', '#B8F7D4']

fig = ff.create_distplot(hist_data, group_labels, curve_type='normal', colors=colors, bin_size=.01)

# 设置图形布局
fig.update_layout(
    title="Allele Frequency",
    yaxis=dict(
        title='Probability density',
        showline=True, showgrid=False,
        linewidth=2, linecolor='gray', ticks='outside',
        tickfont=dict(
            family='Arial',
            size=12,
            color='black',
        )
    ),
    xaxis=dict(
        title='Allele Frequency / %',
        # type='log',  # 对数刻度
        showline=True, showgrid=False,
        range=[0, 1],  # 对数刻度中间值，根据需求调整
        linewidth=2, linecolor='gray', ticks='outside',
        tickfont=dict(
            family='Arial',
            size=12,
            color='black',
        )
    ),
    legend=dict(
        traceorder="normal",
        font=dict(size=12),
    ),
    plot_bgcolor='white',
    yaxis_gridcolor='lightgray', yaxis_gridwidth=0.5,
    xaxis_gridcolor='lightgray', xaxis_gridwidth=0.5,
)

# Save the plot as a PNG file
pio.write_image(fig, 'plot_for_AF_0-1.png')

In [6]:
pip install -U kaleido

Requirement already satisfied: kaleido in /home/zeio/anaconda3/lib/python3.9/site-packages (0.2.1)
Note: you may need to restart the kernel to use updated packages.

### rug plot：
Showing the original discrete distribution of the data

In [7]:
import gc
gc.collect()

44